### ISSUE TITLE
Povezati novo uputstvo sa aplikacijom

### ISSUE THREAD

**Issue by chenejac** [chenejac/cris#12]
Potrebno je linkovati veb stranice uputstva iz CRIS PMF aplikacije.

**Comment by chenejac** [comment]
Reseno sa 10282037cc7e2e6f387e5ac803c18bbed60b73b2
@surladusan molim Vas da probate da se ulogujete kao istrazivac i vidite da li su ove ikonice sa znakom ? dovoljno vidljive i funkcionalne.

**Comment by surladusan** [comment]
Pogledao sam. Sada su ikonice sa znakom ? bolje centrirane. 

ds
