### ISSUE TITLE
UVOD - sređivanje teksta

### ISSUE THREAD

**Issue by surladusan** [chenejac/cris#5]
Tekst Uvoda je znatno skraćen. Cilj je minimum informacija potrebnih za koriščćenje aplikacije. Ažurirati deo koji se odnosi na veb pretraživače i dodati Google Chrome.

**Comment by chenejac** [comment]
@surladusan Slažem se za Google Chrome, ja koristim verziju 96.0.4664.110 i mogu potvrditi da CRIS radi na ovoj verziji, tako da možemo preporučiti i ovaj veb pretraživač (Google Chrome verzija 96.0.4664.110)

**Comment by surladusan** [comment]
У вези тога додао бих за сада следеће:
Препоручује се употреба веб претраживача са којима је апликације тестирана, а то су: Google Chrome, Internet Explorer (до 15. јуна 2020), Microsoft Edge, и Firefox.

Не бих наводио верзије и линкове. Међутим, требало би ово и тестирати. После тестирања додали би ако што буде требало (верзије, линкови).

**Comment by chenejac** [comment]
Ja bih tu stavio samo veb pretraživače koje mi koristimo. Dakle, ja mogu da potvrdim za Google Chrome. Za ove druge ne mogu, ali ovo je i ovako preporuka, ne tvrdimo da ne radi za druge alate.

**Comment by surladusan** [comment]
Prvo, predlažem da usvojimo sledeći tekst:
Препоручује се употреба веб претраживача са којима је апликације тестирана, а то су: Google Chrome и Microsoft Edge.
Drugo, ja sam testirao Microsoft Edge.
Treće, ako se slažeš sa ovim onda bi mogli zatvoriti ovaj Issue.

**Comment by chenejac** [comment]
Rešeno ovim commit-om: https://github.com/chenejac/cris/commit/3ded60fee9828fd09cfe9cbd464e6c04c86237c8
