### ISSUE TITLE
Početna strana

### ISSUE THREAD

**Issue by surladusan** [chenejac/cris#6]
Predlažem sledeće.
Prvo, da se opcija ПМФ zameniti sa CRIS-PMF (latinica). Ovo bi bilo usvojeno ime za CRIS na PMF-u. 
Drugo, dodati sledeći tekst na ovu stranicu: 
CRIS UNS (Current Research Information System University of Novi Sad)
Informacioni sistem naučne delatnosti Univerziteta u Novom Sadu
Opcija CRIS-PMF je javno dostupna.
Takođe su javno dostupni i sledeći linkovi: 
•	Digitalna biblioteka doktorskih disertacija odbranjenih na Univerzitetu u Novom Sadu
•	Prirodno-matematički fakultet u Novom Sadu

**Comment by surladusan** [comment]
Na sajtu ne videm ove promene.

ds

**Comment by chenejac** [comment]
Kada kliknete na CRIS-PMF u glavnom meniju. Ja sam razumeo da je zahtev za tu stranicu??!!

Sincerely,
Dragan Ivanovic

**Comment by surladusan** [comment]
Ne, zahtev je bio za postojeći tekst na stranici https://cris.uns.ac.rs/index.jsf. Dakle, stranicu CRIS-PMF vratiti na staro, a u zakačenom fajlu su date dve opcije za izmenu postojeg teksta. Javi mi koju opciju da usvojima. Meni se sada čini da je druga opcija možda bolja. 

ds
